###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: warn

# docker secret for jwt

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.berhane.me

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

access_control:
  default_policy: deny
  rules:
    - domain: authelia.berhane.me
      policy: bypass
    - domain:
        - "*.berhane.me"
        - "traefik.home"
        - "berhane.me"
      policy: bypass
      networks:
        - 172.30.6.0/24
        - 188.151.10.220    
    - domain:
        - "*.berhane.me"
        - "berhane.me"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: berhane.me # Should match whatever your root protected domain is
  #  redis:
  #  host: redis
  #  port: 6379
  #  # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #  password: redispass

# brute force protection  
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notification.txt
